name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

# 본인 환경에 맞는 또는 본인이 설정한 값으로 설정해야 함
env:
  AWS_REGION: us-east-1
  S3_BUCKET_NAME: seo-s3flask  
  CODE_DEPLOY_APPLICATION_NAME: seo-ciciFlask
  CODE_DEPLOY_DEPLOY_GROUP_NAME: seo-CiciFlaskGroup

permissions:
  contents: read

jobs:
  deploy:	
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v3	

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.Access_key_ID }}
        aws-secret-access-key: ${{ secrets.Secret_access_key }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Upload to AWS S3
      run: |
        aws deploy push \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \

          --s3-location s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip \
          --ignore-hidden-files \
          --source . 

    - name: Deploy to AWS EC2 from S3
      run: |
        aws deploy create-deployment \	
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOY_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,key=$GITHUB_SHA.zip,bundleType=zip
